"""baseline: 初始完整 schema

汇聚当前全部 6 张表（audit_logs/groups/reports/spam_samples/user_settings/warnings）
及其索引、外键、server_default。涵盖旧手写迁移 001-007 的全部 DDL 变更。

- 全新数据库：``alembic upgrade head`` 执行本 revision 建表
- 已有生产库（schema 与本 revision 一致）：``alembic stamp c3d35c9d5221`` 标记到位、不执行 DDL
- downgrade 故意留空：回滚 baseline 等于删表，清理请用 pg_dump 恢复或重建数据卷

Revision ID: c3d35c9d5221
Revises:
Create Date: 2026-08-13 05:04:56.766422
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'c3d35c9d5221'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级数据库结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=True, comment='群组 ID'),
    sa.Column('operator_id', sa.BigInteger(), nullable=True, comment='操作者 ID'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作类型'),
    sa.Column('target_user_id', sa.BigInteger(), nullable=True, comment='目标用户 ID'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='操作详情'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_group_id', 'audit_logs', ['group_id'], unique=False)
    op.create_index('idx_audit_logs_target_user', 'audit_logs', ['target_user_id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='Telegram chat_id'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='群组标题'),
    sa.Column('verification_type', sa.String(length=20), nullable=False, comment='验证方式: math/slider/qa/emoji/captcha/honeypot/random'),
    sa.Column('verification_timeout', sa.Integer(), nullable=False, comment='验证超时时间(秒)'),
    sa.Column('antispam_enabled', sa.Boolean(), nullable=False, comment='是否启用反垃圾'),
    sa.Column('antispam_level', sa.Integer(), nullable=False, comment='反垃圾严格程度: 1-宽松, 2-中等, 3-严格'),
    sa.Column('spam_confirm_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用管理员确认模式（检测到垃圾后等待管理员确认再处罚）'),
    sa.Column('anti_channel_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用反频道马甲(禁止用户以频道身份发言)'),
    sa.Column('activity_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用活跃度系统'),
    sa.Column('activity_skip_threshold', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='活跃度跳过垃圾检测阈值（0=禁用，>0=启用并使用此阈值）'),
    sa.Column('curfew_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否启用宵禁模式'),
    sa.Column('curfew_start_hour', sa.Integer(), nullable=True, comment='宵禁开始小时 (0-23)'),
    sa.Column('curfew_start_minute', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='宵禁开始分钟 (0-59)'),
    sa.Column('curfew_end_hour', sa.Integer(), nullable=True, comment='宵禁结束小时 (0-23)'),
    sa.Column('curfew_end_minute', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='宵禁结束分钟 (0-59)'),
    sa.Column('curfew_timezone_offset', sa.Integer(), server_default=sa.text('8'), nullable=False, comment='时区偏移（相对UTC小时数）'),
    sa.Column('locale', sa.String(length=16), server_default=sa.text("'zh-Hans'"), nullable=False, comment='群组消息语言（BCP 47，如 zh-Hans/zh-Hant/en）'),
    sa.Column('is_whitelisted', sa.Boolean(), nullable=False, comment='是否在白名单中'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('reporter_id', sa.BigInteger(), nullable=False),
    sa.Column('reported_user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('handled_by', sa.BigInteger(), nullable=True),
    sa.Column('handled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_group_id'), 'reports', ['group_id'], unique=False)
    op.create_index(op.f('ix_reports_reported_user_id'), 'reports', ['reported_user_id'], unique=False)
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('spam_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('is_spam', sa.Boolean(), nullable=False, comment='是否为垃圾信息'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='置信度分数'),
    sa.Column('labeled_by', sa.BigInteger(), nullable=True, comment='标注者 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spam_samples_created_at', 'spam_samples', ['created_at'], unique=False)
    op.create_index('idx_spam_samples_is_spam', 'spam_samples', ['is_spam'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Telegram 用户 ID'),
    sa.Column('locale', sa.String(length=16), server_default=sa.text("'zh-Hans'"), nullable=False, comment='用户私聊语言偏好（BCP 47，如 zh-Hans/zh-Hant/en）'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('warnings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False, comment='群组 ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='被警告用户 ID'),
    sa.Column('reason', sa.Text(), nullable=True, comment='警告原因'),
    sa.Column('issued_by', sa.BigInteger(), nullable=True, comment='警告发起者 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_warnings_created_at', 'warnings', ['created_at'], unique=False)
    op.create_index('idx_warnings_group_user', 'warnings', ['group_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """baseline 不可回滚。

    回滚 baseline 等同于删除全部表与数据，风险极高且不可逆。
    灾难恢复应使用 pg_dump 备份（见 scripts/backup.py）；清理环境用
    ``docker-compose down -v`` 重建数据卷。故此处显式抛错，防止
    ``alembic downgrade base`` 静默成功后留下无版本标记的孤儿表，
    导致下次 ``upgrade head`` 重复建表失败。
    """
    raise RuntimeError(
        "baseline 不可回滚（回滚将删除全部表与数据）。"
        "灾难恢复请用 pg_dump 备份恢复或 docker-compose down -v 重建数据卷。"
    )
